### ISSUE TITLE
Graph & context replaces context instead of appending

### ISSUE THREAD

**Issue by stew** [oncue/quiver#6]
scala> empty[String,Unit,Int].addNode(LNode("one", ())).addNode(LNode("two", ())).addNode(LNode("three", ())) & Context(Vector(), "one", (), Vector((2, "two"))) & Context(Vector(), "one", (), Vector((3, "three")))
    res8: quiver.Graph[String,Unit,Int] = 
    one:()->[(3,three)]
    two:()->[]
    three:()->[]

I would expect to end up with both edges to two and three after calling & twice.

I believe this is this suspect line: https://github.com/oncue/quiver/blob/master/core/src/main/scala/Graph.scala#L75

I think this will have to modify the entry instead of adding a new one.

**Comment by runarorama** [comment]
I agree this is at least a documentation bug. That said, the semantics of `&` are supposed to be as follows:

```
g & c decomp c.vertex == Decomp(Some(c), g)
```

So `decomp` and `&` (alias `embed`) are supposed to be deterministic inverses of each other in that sense. If `&` were to do a merge, this would no longer be the case.

Martin Erwig's original FGL library actually throws an exception when you `embed` a context whose vertex already exists in the graph. Likewise it throws an exception when you try to `decomp` a vertex that isn't in the graph.

So maybe the correct thing here is to have `embed` return an `Option`, which is `None` if you're trying to re-add a vertex.

The operation that does what you want is `Graph.union`. We should probably have a convenience function for converting a `Context` to a `Graph`.

**Comment by runarorama** [comment]
Whatever we end up doing, we should probably not do what we're currently doing, which is to blithely overwrite a context that already exists. Thoughts about using `Option` here?

**Comment by runarorama** [comment]
Related: https://github.com/oncue/quiver/blob/master/core/src/main/scala/Graph.scala#L179

**Comment by runarorama** [comment]
Addressed in https://github.com/oncue/quiver/pull/7
